- name: Restart server
  command: shutdown -r now "Reboot triggered by Ansible"
  async: 0
  poll: 0
  ignore_errors: true
- name: Wait for server to back online
  local_action:
    wait_for
      host={{ inventory_hostname }}
      port=22
      delay=1
      timeout=300
  sudo: false

- name: reload systemctl daemon
  command: systemctl daemon-reload

- name: restart docker daemon
  service:
    name: docker.service
    enabled: yes
    state: restarted

- name: stop and disable firewall on centos
  service:
    name: firewalld
    enabled: no
    state: stopped
