---

#- debug: msg="{{ inventory_hostname }}"

- name: upgrade all packages
  yum: name=* state=latest
  notify:
    - Restart server
    - Wait for server to back online

- name: show kernal version
  command: uname -r
  register: kernal

- debug: msg="{{ kernal}}"

- name: add docker yum repository
  yum_repository:
    name: Docker-Centos-7
    description: Docker repository for Centos 7
    baseurl: https://yum.dockerproject.org/repo/main/centos/$releasever/
    enabled: yes
    gpgkey: https://yum.dockerproject.org/gpg
    gpgcheck: yes
    state: present
- name: Install Docker CS Engine
  yum:
    name: docker-engine
    state: present
  notify:
    - reload systemctl daemon
    - restart docker daemon
