---

- name: upgrade all packages
  yum: name=* state=latest
#  notify:
#    - Restart server
#    - Wait for server to back online
  register: yum_upgrade

- name: restart machine
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  sudo: true
  ignore_errors: true
  when: yum_upgrade.changed

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} port=22 delay=30 timeout=300
  sudo: false

- name: show kernal version
  command: uname -r
  register: kernal

- debug: msg="{{ kernal }}"

- name: show release version
  command: cat /etc/redhat-release
  register: release

- debug: msg="{{ release }}"

- name: add docker yum repo
  yum_repository:
    name: docker-centos-7
    description: Docker repo for centos 7
    baseurl: https://yum.dockerproject.org/repo/main/centos/$releasever/
    enabled: yes
    gpgkey: https://yum.dockerproject.org/gpg
    gpgcheck: yes
    state: present

- name: install docker engine
  yum:
    name: docker-engine
    state: present
  notify:
    - reload systemctl daemon
    - restart docker daemon

- name: create Docker configuration directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: u=rwx,go=rx

- name: install Docker Engine settings
  template:
    src: "{{item}}"
    dest: /etc/systemd/system/docker.service.d
  notify:
    - reload systemctl daemon
    - restart docker daemon
    - stop and disable firewall on centos
  with_items:
    - docker.conf

- name: check docker installation
  command: docker info
  register: docker_info
- debug: msg="{{ docker_info }}"
