---

- name: create node for DCOS
  command: /bin/bash curl-create-node.sh
  args:
    chdir: "/root/gh/gic-dcos-auto/playbook/scripts"
  register: curl_create_node_result

- name: show "create node for DCOS" result
  debug: var=curl_create_node_result

- set_fact: create_node_task_id="{{ (curl_create_node_result.stdout | from_json)['task_id'] }}"

- name: get task status by task id
  command:  /bin/bash curl-get-task-status.sh {{ hostvars[inventory_hostname].create_node_task_id }}
  args:
    chdir: "/root/gh/gic-dcos-auto/playbook/scripts"
  register: task_status
  until: task_status.stdout.find("FINISH") != -1
  retries: 30
  delay: 60

- debug: msg="Task {{ hostvars[inventory_hostname].create_node_task_id }} to create node is Done"

